### ISSUE TITLE
isInSubnet not matching ipv6 addresses in format ::ffff:ipv4 against ipv4 cidr

### ISSUE THREAD

**Issue by c0deright** [natesilva/is-in-subnet#2]
Hi,

> ```js
> > TRUSTED_ADDRESSES = ["172.16.0.0/16"]
> > isInSubnet('172.16.10.10', TRUSTED_ADDRESSES) // true
> > isInSubnet('::ffff:172.16.10.10', TRUSTED_ADDRESSES) // false
> ```

IMHO the second check should return true, too.

Depending on the node version e.g. Express Framework will return an IPv4 address or an encapsulated IPv4 address inside an IPv6 address (with prefix ::ffff:) for the client IP address. isInSubnet should return the same value for both variants when checked against the same IPv4 CIDR block (same when checked against an IPv4-in-IPv6 block I guess).

In this example I would have to add `::ffff:172.16.0.0/112` to TRUSTED_ADDRESSES for the 2nd check to return true to be compatible with node versions returning ipv6 addresses.

**Comment by natesilva** [comment]
This is fixed starting in version 1.9.0. An IPv4 mapped address will be compared against both IPv4 and IPv6 subnets.
