### ISSUE TITLE
How to browserify 

### ISSUE THREAD

**Issue by laduke** [natesilva/is-in-subnet#4]
Thanks for writing this module!

Browserify stubs out node/net with an empty object, so .isIp doesn't exist if you try to run this in the browser. 

If anyone runs into this problem, they can do `browserify -r net-browserify-stub:net ...`

If this projected added
```
  "browser": {
    "net": "net-browserify-stub" 
  },
```

to it's package.json, then it would happen automatically for dependants durring browserifyification. I think other bundlers use the browser field too. 

Have fun!

**Comment by natesilva** [comment]
This should be updated to not depend on the Node 'net' module. The `isIP` logic that Node uses could be built-in.

**Comment by natesilva** [comment]
`is-in-subnet` no longer depends on the Node.js `net` module and it is now completely self-contained, with no dependencies on Node built-in modules.

I believe this should make it work better with Browserify.

In addition, for users who want to use this in a browser but don’t have an NPM-based workflow, I’ve produced pre-bundled versions that can be loaded from the jsDelivr CDN (documented on the README.md).

Thank you!
